### ISSUE TITLE
"Slider Simulation" and "Parm Range" not working.

### ISSUE THREAD

**Issue by paulmueller** [paulmueller/PyCorrFit#133]
Cause by recent removal of `FloatSpin` from `pycorrfit.edclasses`.

**Comment by mestia** [comment]
Hi Paul, while testing the debian package for pycorrfit 0.9.1 I am get the following traceback, 
when I load a session and click on "Set range".

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pycorrfit/page.py", line 698, in OnSetRange
    self.parent.RangeSelector = tools.RangeSelector(self)
  File "/usr/lib/python2.7/dist-packages/pycorrfit/tools/parmrange.py", line 35, in __init__
    self.OnPageChanged(self.Page)
  File "/usr/lib/python2.7/dist-packages/pycorrfit/tools/parmrange.py", line 118, in OnPageChanged
    self.FillPanel()
  File "/usr/lib/python2.7/dist-packages/pycorrfit/tools/parmrange.py", line 58, in FillPanel
    left = edclasses.FloatSpin(self.panel, digits=7, increment=.1)
AttributeError: 'module' object has no attribute 'FloatSpin'

Is this issue about that ? 

Thanks, 
Alex

**Comment by paulmueller** [comment]
yes, this will be fixed in 0.9.2
