### ISSUE TITLE
traceback when trying to Fit

### ISSUE THREAD

**Issue by mestia** [paulmueller/PyCorrFit#140]
HI, 
with the version 0.9.3 I am getting the following traceback when loading a test session and clicking Fit.
Does it work for you ? 

Thanks, 
Alex

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pycorrfit/page.py", line 330, in Fit_function
    Fit(self.corr)
  File "/usr/lib/python2.7/dist-packages/pycorrfit/fcs_data_set.py", line 720, in __init__
    self.minimize()
  File "/usr/lib/python2.7/dist-packages/pycorrfit/fcs_data_set.py", line 1332, in minimize
    params = self.get_lmfitparm()
  File "/usr/lib/python2.7/dist-packages/pycorrfit/fcs_data_set.py", line 1176, in get_lmfitparm
    max=self.fit_bound[pp][1],
  File "/usr/lib/python2.7/dist-packages/lmfit/parameter.py", line 55, in add
    min=min, max=max, expr=expr))
  File "/usr/lib/python2.7/dist-packages/lmfit/parameter.py", line 32, in __setitem__
    if not valid_symbol_name(key):
  File "/usr/lib/python2.7/dist-packages/lmfit/astutils.py", line 203, in valid_symbol_name
    return NAME_MATCH(name) is not None
TypeError: expected string or buffer
```

**Comment by paulmueller** [comment]
Hi,
which version of lmfit are you using?

The [Windows build](https://ci.appveyor.com/project/paulmueller/pycorrfit/build/1.0.280/job/5jb91255wn7euncv#L287) uses lmfit 0.9.2.

I also use lmfit 0.9.2 on Ubuntu.

**Comment by mestia** [comment]
Hi, 
Yes, that was the case, for testing I used Jessie and the lmfit version 0.8.0. It works with 0.9.2.
Thank you!
