### ISSUE TITLE
Problem with running 0.8.4 on a 10.6.8 mac

### ISSUE THREAD

**Issue by phubert52** [paulmueller/PyCorrFit#88]
Hi
I’m trying to run PyCorrFit 0.8.4 on a OSx 10.6.8 mac, installed from the app.zip

Upon start, I get an error message in the terminal, but the PyCorrFit window opens

“Checking module versions...
 OK: matplotlib v. 1.2.1 | 1.0.0 required
 OK: NumPy v. 1.7.1 | 1.5.1 required
 OK: PyYAML v. 3.11 | 3.09 required
 OK: SciPy v. 0.12.0 | 0.8.0 required
 OK: sympy v. 0.7.3 | 0.7.2 required
 OK: wxPython v. 2.8.12.1 | 2.8.10.1 required
I do not know what to do with this argument: /Applications/PyCorrFit.app/Contents/MacOS/PyCorrFit.bin”

When I try to load data from one of the tutorial files, PyCorrFit freezes :

![image](https://cloud.githubusercontent.com/assets/10419345/5629769/4d769a28-95b7-11e4-92ff-22bafb5d2010.png)

and I get the following error messages :

“Traceback (most recent call last):
  File "/Users/paul/repos/PyCorrFit/build/PyCorrFit_mac/out00-PYZ.pyz/frontend", line 1047, in OnLoadBatch
  File "/Users/paul/repos/PyCorrFit/build/PyCorrFit_mac/out00-PYZ.pyz/wx._windows", line 2943, in Update
wx._core.PyAssertionError: C++ assertion "value <= m_maximum" failed at /BUILD/wxPython-src-2.8.12.1/src/generic/progdlgg.cpp(337) in Update(): invalid progress value”

And I do not get these error messages with the previous 0.8.3-alpha1 release, this one opens the .fcs demo files, but not my PicoQuant .pt3 files.

I tried to reinstall Python and other requirements, to no avail. Could you help me solve this problem ?

Best regards
Pierre

**Comment by phubert52** [comment]
Many thanks. I'm looking forward to the new release.
I also tested the Windows version (both on XP and 7pro), I get the same error messages. 

Best
Pierre
